# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=7)),
                ('type', models.CharField(max_length=15)),
                ('card_name', models.CharField(max_length=200)),
                ('mana_cost', models.IntegerField()),
                ('rarity', models.CharField(max_length=12)),
                ('artist', models.CharField(max_length=100)),
                ('collectible', models.BooleanField()),
                ('flavor_text', models.TextField()),
                ('card_set', models.CharField(max_length=30)),
                ('dust_cost', models.IntegerField()),
                ('dust_value', models.IntegerField()),
                ('golden_dust_cost', models.IntegerField()),
                ('golden_dust_value', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
                ('mechanics', models.TextField()),
                ('card_text', models.TextField()),
                ('player_class', models.CharField(max_length=12)),
                ('weapon_durability', models.IntegerField()),
            ],
        ),
    ]
