# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dust_cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dust_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='golden_dust_cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='golden_dust_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='mechanics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='player_class',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='weapon_durability',
            field=models.IntegerField(blank=True),
        ),
    ]
