# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0002_auto_20160410_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dust_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='dust_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='golden_dust_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='golden_dust_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='mechanics',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='player_class',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='weapon_durability',
            field=models.IntegerField(null=True),
        ),
    ]
