# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0003_auto_20160410_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='weapon_durability',
        ),
    ]
