# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0004_remove_card_weapon_durability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='mechanics',
        ),
    ]
