# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0006_auto_20160410_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardsearch.Card')),
                ('attack', models.IntegerField(null=True)),
                ('health', models.IntegerField(null=True)),
            ],
            bases=('cardsearch.card',),
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardsearch.Card')),
                ('card_text', models.TextField(null=True)),
            ],
            bases=('cardsearch.card',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardsearch.Card')),
                ('attack', models.IntegerField(null=True)),
                ('weapon_durability', models.IntegerField(null=True)),
            ],
            bases=('cardsearch.card',),
        ),
        migrations.RemoveField(
            model_name='card',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='card',
            name='health',
        ),
    ]
