# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0007_auto_20160411_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minion',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='minion',
            name='health',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='attack',
        ),
    ]
