# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsearch', '0008_auto_20160411_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='minion',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='minion',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='attack',
            field=models.IntegerField(null=True),
        ),
    ]
